export { default as Navbar } from "./navbar/Navbar";
export { default as Header } from "./header/Header";
export { default as Content } from "./content/Content";
export { default as Footer } from "./footer/Footer";
export { default as HotelList } from "./hotel-list/HotelList";
export { default as SearchList } from "./search-list/SearchList";
export { default as DetailsHeader } from "./details-header/DetailsHeader";
export { default as DetailsGallery } from "./details-gallery/DetailsGallery";
export { default as DetailsFooter } from "./details-footer/DetailsFooter";
